### PR TITLE
document/fix unchecked operations

### LINKED ISSUE #97: [virtio-queue] document unchecked_* operations safety
We have a couple of `unchecked_*` operations that would benefit from a comment on why they are safe to use, e.g. https://github.com/rust-vmm/vm-virtio/blob/main/crates/virtio-queue/src/lib.rs#L581.

### PR DESCRIPTION
**Pull request by lauralt**
Fixes #97 #99

### CODE REVIEW

File: crates/virtio-queue/src/state.rs [hunk 1]
```diff
@@ -74,9 +74,16 @@ impl QueueState {
         val: u16,
         order: Ordering,
     ) -> Result<(), Error> {
+        // The multiplication can not overflow an u64 since we are multiplying an u16 with a
```
Comment (andreeaflorescu) [inline crates/virtio-queue/src/state.rs:77]: Can we combine these two comments into one saying that the following operations cannot overflow because they're working with small numbers? I find the comments to be too much and getting in the way of the readability. Same for the other ones where there are 2 subsequent operations.

Comment (lauralt) [reply crates/virtio-queue/src/state.rs]: Done, I also combined some of the operations.

**Review by andreeaflorescu — APPROVED** [review]

**Review by jiangliu — APPROVED** [review]
